// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmv01xQJmUeTYVIU9HA0mBGBpUuYuazBQ',
    appId: '1:62186532400:web:f8f5401c291766c0e287f5',
    messagingSenderId: '62186532400',
    projectId: 'mi-finanzas-app-pp',
    authDomain: 'mi-finanzas-app-pp.firebaseapp.com',
    storageBucket: 'mi-finanzas-app-pp.firebasestorage.app',
    measurementId: 'G-GT3Y6H7N4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsQ1PmC49eqg2sB36hK6wAcL1BR1m8S1M',
    appId: '1:62186532400:android:6036c82be493d121e287f5',
    messagingSenderId: '62186532400',
    projectId: 'mi-finanzas-app-pp',
    storageBucket: 'mi-finanzas-app-pp.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmv01xQJmUeTYVIU9HA0mBGBpUuYuazBQ',
    appId: '1:62186532400:web:8570a36eb2e0a356e287f5',
    messagingSenderId: '62186532400',
    projectId: 'mi-finanzas-app-pp',
    authDomain: 'mi-finanzas-app-pp.firebaseapp.com',
    storageBucket: 'mi-finanzas-app-pp.firebasestorage.app',
    measurementId: 'G-0GXFF8C4G2',
  );
}
